export const navbarQuery = `*[_type == "navbar"][0]`
export const heroQuery = `*[_type == "hero"][0]`
export const searchQuery = `*[_type == "search"][0]`
export const dataTrustQuery = `*[_type == "dataTrust"][0]`
export const statisticsQuery = `*[_type == "statistics"][0]`
export const howItWorksQuery = `*[_type == "howItWorks"][0]`
export const dataProcessingQuery = `*[_type == "dataProcessing"][0]`
export const ourEdgeQuery = `*[_type == "ourEdge"][0]`
export const whoWeServeQuery = `*[_type == "whoWeServe"][0]`
export const ecosystemQuery = `*[_type == "ecosystem"][0]`
export const footerQuery = `*[_type == "footer"][0]`
